### Get a route
POST https://nzemrgdvuxghaitjyojn.supabase.co/rest/v1/rpc/route
Content-Type: application/json
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZW1yZ2R2dXhnaGFpdGp5b2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQyMDM3MzMsImV4cCI6MTk3OTc3OTczM30.hNB_yvwYCn-5b65jnTX6wCsm7B1JjzKIflIEtMvzgEM

{
  "loc_from": "1311 E 18th", 
  "loc_to": "1116 Bute" 
}


### Get an address from the table
GET https://nzemrgdvuxghaitjyojn.supabase.co/rest/v1/addressess
  ?select=civic_number,std_street
  &fts=wfts.1116 Bute
Content-Type: application/json
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZW1yZ2R2dXhnaGFpdGp5b2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQyMDM3MzMsImV4cCI6MTk3OTc3OTczM30.hNB_yvwYCn-5b65jnTX6wCsm7B1JjzKIflIEtMvzgEM


### get an address from autocomplete
GET https://nzemrgdvuxghaitjyojn.supabase.co/rest/v1/rpc/addressautocomplete?search=11%20But
Content-Type: application/json
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZW1yZ2R2dXhnaGFpdGp5b2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQyMDM3MzMsImV4cCI6MTk3OTc3OTczM30.hNB_yvwYCn-5b65jnTX6wCsm7B1JjzKIflIEtMvzgEM
